### ISSUE TITLE
Adequando arquitetura para autenticação Single Sign On

### ISSUE THREAD

**Issue by ricardocanela** [fga-eps-mds/2018.2-iFood#118]
A autenticação receberá uma modificação, com a finalidade de não ser necessário replicar o secret do jwt entre os demais grupos. Para isso, cada requisição à API Gateway fará uma verificação do token no Login-Microservice.

Nossa autenticação funcionará da seguinte maneira:
- Ao realizar o login, o front-end recebe e armazena o token e as informações do usuário, como id e nome
- Para cada requisição feita a API Gateway deve ser enviado do front-end o token e as informações do usuário armazenadas. Na API Gateway Será validado o token pela rota verify-token do Login-Microservice e assim que for confirmado poderá realizar o processamento utilizando as informações do usuário

Nosso Login-Microsservice atual conta com o end-point login que já retorna o token e as informações do usuário. É necessário modificar o front-end para armazenar além do token, as informações do usuário.

O Login-Microservice também já tem implementado a rota verify-token que recebe um token. Caso o token seja válido, ele retorna o token, caso contrário retorna uma mensagem de erro.
É necessário implementar uma função no API Gateway (verify_token) que será chamada dentro das outras funções para realizar a autenticação antes do processamento da função

**Comment by gustavolima00** [comment]
Dentro de algumas outras issues essa função já foi implementada, irei fechar a issue :+1: .
