### ISSUE TITLE
Documento de Visão

### ISSUE THREAD

**Issue by lugope** [fga-eps-mds/2018.2-iFood#14]
Formato do documento de visão pode ser consultado no site da IBM:
https://www.ibm.com/support/knowledgecenter/pt-br/SSWMEQ_4.0.6/com.ibm.rational.rrm.help.doc/topics/r_vision_doc.html

**Comment by wparaujo** [comment]
Documento de visão será feito pela equipe de desenvolvimento (MDS), baseado em documentos já criado faltando inserir no github pages.
Documentos de referência para visão:

* Personas
* Canvas de Proposta de Valor
* Business model Canvas
* TAP
* EAP

**Comment by juniopereirab** [comment]
Tópicos a serem feitos no Documento de Visão

- [ ] Introdução

- [ ] Posicionamento

- [ ] Descrições da parte interessada e dos usuários

- [ ] Visão Geral do Produto

- [ ] Recursos do Produto

- [ ] Restrições
