### ISSUE TITLE
Código

### ISSUE THREAD

**Issue by mbslet** [fga-eps-mds/2018.2-iFood#77]
Pessoal vocês já começaram a codar algo para o projeto? Back ou front

**Comment by lucasca73** [comment]
Já sim 😉, os repositórios dos microserviços são esses aqui:

* Microserviço Produto - https://github.com/fga-eps-mds/2018.2-FGAPP-produto
* Microserviço Login - https://github.com/fga-eps-mds/2018.2-FGAPP-login
* Microserviço Vendas - https://github.com/fga-eps-mds/2018.2-FGAPP-vendas
* Microserviço Vendedor - https://github.com/fga-eps-mds/2018.2-FGAPP-vendedor

O front foi configurado Quarta-feira. Dai estamos começando aos poucos.

* FRONT - https://github.com/fga-eps-mds/2018.2-FGAPP-FrontEnd

Carla mencionou que não deveria ter repositórios de documentação né. Mas esse repo aqui será configurado pro API Gateway, estamos planejando de adicioná-lo nesse final de sprint (hoje).

**Comment by mbslet** [comment]
Uhuu! Mandaram bem então, saquei mais ou menos a distribuição de vocês, vou dar uma olhadinha nesses ai. Obrigada pelo esclarecimento! :smile:
